### ISSUE TITLE
Change implementation of filter function

### ISSUE THREAD

**Issue by jakopako** [jakopako/event-crawler#20]
I think it would be better to have separate field `filters`  per crawler like so:
```
filters:
  - field: "title"
    regex: "some regex"
  - field: "comment"
    regex: "some other regex"
```
This would make the implementation easier since we could simply loop over the array of filter items and apply the filter to the corresponding field. On the other hand we would still need sth like a switch case to map the field string to the corresponding field in the crawler struct... Think about this and improve the implementation.
